<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Practice has been created' => 'Erfahrung hinzugefügt',
    'Core Competence Analyser' => '@@Kernkompetenzen Analysieren@@',
    'Get started with you analyses' => '@@Starten Sie mit der Analyse@@',
    'Welcome!' => '@@Herzlich Willkommen!@@',
    'to the core compentence analyser' => '@@zum Kernkompetenzen Finder@@',
    'Add Practice' => 'Erfahrung hinzufügen',
    'Comment' => 'Kommentar',
    'Competence' => 'Kompetenz',
    'Competence Factor' => 'Kopetenz Faktor',
    'Create a profile' => 'Neues Profil anlegen',
    'Created At' => 'Erzeugt am',
    'Creation time' => 'Angelegt am',
    'Edit' => 'Editieren',
    'Edit Practice' => 'Erfahrung bearbeiten',
    'Expertise' => 'Expertise',
    'Fun Factor' => 'Spaß',
    'Manage profiles' => 'Profile Verwalten',
    'Practice' => 'Erfahrung',
    'Practice Name' => 'Erfahrung-Bezeichnung',
    'Practicename' => 'Erfahrung-Bezeichnung',
    'Profile' => 'Profil',
    'Profile ID' => 'Profil ID',
    'Profile Name' => 'Profil-Name',
    'Profile has been created' => 'Profil angelegt',
    'Profile name' => 'Profil Name',
    'Results' => 'Ergebnis',
    'Save' => 'Speichern',
    'Specifics' => 'Fachwissen',
    'Update Profile' => 'Profil aktualisieren',
    'User' => 'Benutzer',
    'View Results' => 'Ergebnisse anzeigen',
    '{0, date, MMMM dd, YYYY HH:mm}' => '{0, date, dd. MMMM YYYY \'um\' HH:mm}',
];
